set -g @plugin 'o0th/tmux-nova'

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

# Pane borders
set -g @nova-pane-active-border-style "#f3bc70"
set -g @nova-pane-border-style "#424c5e"

# Status bar
set -g @nova-status-style-bg "#0d0e1f"
set -g @nova-status-style-fg "#f3bc70"
set -g @nova-status-style-active-bg "#2e344d"
set -g @nova-status-style-active-fg "#f3bc70"

set -g @nova-pane "#I:#W"
set -g @nova-pane-justify "left"

# Whoami segment
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#f3bc70 #151726"

# Session segment
set -g @nova-segment-session "#S"
set -g @nova-segment-session-colors "#0d0e1f #f3bc70"

# SSID
set -g @nova-segment-ssid "󰝤󰝤󰝤󰝤"
set -g @nova-segment-ssid-colors "#151726 #151726"

# Battery
set -g @nova-segment-battery "󰝤󰝤󰝤󰝤"
set -g @nova-segment-battery-colors "#424c5e #424c5e"

# Time
set -g @nova-segment-time "%H:%M"
set -g @nova-segment-time-colors "#76859b #151726"

# Date
set -g @nova-segment-date "%Y/%m/%d"
set -g @nova-segment-date-colors "#f3bc70 #0d0e1f"

set -g @nova-rows 0
set -g @nova-segments-0-left "whoami session"
set -g @nova-segments-0-right "ssid battery time date"
