# Base packages installed on all systems
# These packages are included regardless of host or modules

description: Base system packages

packages:
  # Essential base system
  - cuda

  # Basic tools (uncomment as needed)
  - 7zip
  - discord
  - eza
  - fd
  - fzf
  - fzf-tab-source
  - helix
  - keepassxc
  - kitty
  - konsave
  - libreoffice-still
  - neovim
  - obsidian
  - python312
  - tk
  - ttf-iosevka-nerd
  - ttf-atkinson-hyperlegible-next
  - freedownloadmanager
  - windsurf
  - waterfox-bin
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - zsh
  - python-pywal
  - python-pdm
  - yazi
  - yt-dlp
  - spotify
  - xclip
  - xsel
  - okular
  - telegram-desktop
  - gtk-engine-murrine
  - gtk-engines
  - helium-browser-bin
  - plasma6-applets-plasmusic-toolbar
  - python-pip
  - tree
  - cava
