# Base packages installed on all systems
# These packages are included regardless of host or modules

description: Base system packages

packages:
  # Essential base system
  - base
  - base-devel
  - cuda

  # Kernel (uncomment the one you use)
  # - linux              # Standard kernel
  # - linux-hardened     # Security-focused kernel

  # Firmware (usually needed)
  # - linux-firmware

  # Basic tools (uncomment as needed)
  - neovim
  - freedownloadmanager
  - keepassxc
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - fzf-tab-source
  - zsh
  - zed
  - zoom
  - waterfox
  - windsurf
  - xdg-ninja
  - obsidian
  - libreoffice-still
  - ttf-iosevka
  - ttf-atkinson-hyperlegible-next
  - python-pywal
  - python-pdm
  - brave-bin
  - docker
  - docker-compose
  - fzf
  - yazi
  - helix
  - yt-dlp
