# Base packages installed on all systems
# These packages are included regardless of host or modules

description: Base system packages

packages:
  # Essential base system
  - cuda we need to download specific ones

  # Apps
  - discord
  - spotify
  - telegram-desktop
  - obsidian
  - libreoffice-still
  - okular
  - zotero-bin
  - waterfox-bin
  - helium-browser-bin
  - freedownloadmanager

  # Dev
  - python312
  - python-pip
  - python-pdm
  - nodejs
  - npm
  - ruff
  - pre-commit
  - android-tools

  # cli
  - eza
  - fd
  - fzf
  - fzf-tab-source
  - ripgrep
  - yazi
  - tree
  - tmux
  - fastfetch
  - cava
  - yt-dlp

  # editors:
  - neovim
  - helix
  - vscodium

  # shell:
  - zsh
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - kitty
  - espanso-wayland

  # ui:
  - ttf-iosevka-nerd
  - ttf-atkinson-hyperlegible
  - gtk-engine-murrine
  - gtk-engines
  - plasma6-applets-plasmusic-toolbar
  - konsave
  - sddm-kcm

  # security:
  - keepassxc

  # utils:
  - 7zip
  - xclip
  - xsel

  # misc:
  - windsurf
  - tk
